### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by LL-Cosmo** [gnolang/bounties-old#1]
https://archive.interchain.io/

**Comment by LL-Cosmo** [comment]
From Sunny



-Moonboy-

**Comment by jaekwon** [comment]
It was suggested that the bounty go to the ICF; it was the entity responsible for maintaining it until Sunny found it.
Sunny was the referrer, and the ICF was the primary, and I suppose a 20% cut to the referrer is fair.  Let's get their OSMO addresses!

**Comment by LL-Cosmo** [comment]
![Uploading Screenshot_20210718-140049__01.jpg…]()

**Comment by LL-Cosmo** [comment]
![Screenshot_20210718-140049__01](https://user-images.githubusercontent.com/79336608/126065148-bacb66a0-fd68-499c-bddc-6ed9a3ce25b0.jpg)

**Comment by LL-Cosmo** [comment]
Another database
https://cosmos.quicksync.io/

**Comment by jaekwon** [comment]
sounds great, thank you LL-Cosmo!  BTW please share your osmosis addr.

**Comment by LL-Cosmo** [comment]
👍🏻

osmo1cnskgpm8pasf628kzqs5vqlk5qk0y624lkucj4

**Comment by LL-Cosmo** [comment]
> 👍🏻
> 
> osmo1cnskgpm8pasf628kzqs5vqlk5qk0y624lkucj4

**Comment by LL-Cosmo** [comment]
ION Governance working community research revealed that 17.605 $Ion out of 21.294 are currently unclaimed, which means that only 3.689 $Ion are currently in circulation and potentially tradeable.

**Comment by LL-Cosmo** [comment]
https://github.com/osmosis-labs/osmosis/blob/15e7725510a908b622ac7b19e00cc474e8b83aec/cmd/osmosisd/cmd/genaccounts.go

**Comment by LL-Cosmo** [comment]
https://github.com/sunnya97/sunnya97.github.io/blob/master/fsociety.zip

**Comment by LL-Cosmo** [comment]
ion.wtf

requires password

Sunny's hint is:
right in front of your eyes

**Comment by LL-Cosmo** [comment]
[Uploading fsociety.zip…]()




Password: 🧿

**Comment by LL-Cosmo** [comment]
Original ion airdrop distribution script file was discovered by link ion.wtf which was linked on Sunny's AI bot Twitter
https://twitter.com/sunnya97_bot
File needed password for access.

From ION governance working group:
Aug.9th
Sunny gave it hint for password:
right in front of your eyes.

Guy called Alec cracks the pw at the same day and it was 🧿 emoji

**Comment by LL-Cosmo** [comment]
So files can be found from here
https://github.com/sunnya97/sunnya97.github.io/blob/master/_site/fsociety.zip

Password: 🧿

(works with mac, maybe ios, not with windows/android. Guess that depends different kind of shortcuts which is created for different platforms for the same emoji )

**Comment by ajofuk** [comment]
Nostradamus has uploaded an unziped version to his github at the below link, for anyone struggling to use the emoji password.
https://github.com/Nostradamus411/ion-airdrop-code

Seems to generally follow the deductions of rowan's manual analysis. Sunny has confirmed in TG that voting on prop 14 not being included for distribution was an error on his part rather than intentional. The fsociety.zip had been sat on Sunny's github since launch, waiting for us to find it!

Alec

**Comment by jaekwon** [comment]
Please check this summary https://github.com/gnolang/bounties/blob/main/bounties/001_cosmoshub_blockchain_data/README.md
