### ISSUE TITLE
Jaekwon 5th bounty

### ISSUE THREAD

**Issue by catShaark** [gnolang/bounties-old#11]
I made some modification in gnolang to implement ed25519 key. Details in this repo
https://github.com/romelukaku/Bounty5

**Comment by jaekwon** [comment]
thanks you, please check my comments I made here: https://github.com/notional-labs/gno/commit/31dc90bdb18ea476e07b9927fad8022118cca421#

In addition to those comments, it should be a PR onto gnolang/gno.  I think the approach here is useful, so likely will be incorporated into the final PR.

In addition, lets continue discussion of the general goal here: https://github.com/gnolang/bounties/issues/15

**Comment by jaekwon** [comment]
UPDATE: I think we should continue off of this fork though: https://github.com/gnolang/bounties/issues/14
