### ISSUE TITLE
scraped data

### ISSUE THREAD

**Issue by catShaark** [gnolang/bounties-old#2]
scraped data and scripts of cosmos-hub 1-4 gov module

**Comment by catShaark** [comment]
the data is in the file gaia_proposals.json in this repo https://github.com/romelukaku/cosmos-gov-scrape-to-find-ions

**Comment by jaekwon** [comment]
BTW please share your osmosis addr, or privately.

**Comment by catShaark** [comment]
osmo1jnqptkzgx4wpaa9kxqsfq2pfh2d56let3xmefu
here is my osmo addr

**Comment by jaekwon** [comment]
thank you, please check this summary: https://github.com/gnolang/bounties/blob/main/bounties/001_cosmoshub_blockchain_data/README.md
