### ISSUE TITLE
Questions about bounty #7

### ISSUE THREAD

**Issue by jackthgu** [gnolang/bounties-old#23]
Hello, I have a few questions about this bounty program #7.
I think that the snapshot fork mentioned here saves the current gno state to the cosmos hub, and provides useful functions for the saved state.
1. Are my thoughts above correct?
2. Is the implementation to create a new binary like logjack or gnokey?
3. Can I get a review of the process that I am developing correctly? (before pr)
4. If the purpose of this bounty is to create a new binary, can I have a specification that specifies the functions?

Thank you!

**Comment by jaekwon** [comment]
1. it's maybe the other way around; saves the current cosmos hub state. sorry for any confusion, more clarifications here: https://github.com/gnolang/bounties/issues/24#issuecomment-1094298684
2. probably
3. yes it is required. but see https://github.com/gnolang/bounties/issues/24#issuecomment-1094298684
