### ISSUE TITLE
Manual research

### ISSUE THREAD

**Issue by RowanUtrecht** [gnolang/bounties-old#3]
I've manually researched about 40 address on Mintscan (including the biggest receivers of the airdrop)

I found a match on
- Staking to Sikka at the snapshot gives at least 1 ION
- NOT ANY LONGER VALID-period of staking to Sikka (people that staked more then 1 year to Sikka get 2 ION-
- The amount of ION you get from staking to Sikka, is depending on the amount of Cosmos hubs a wallet staked. There are 3 hubs (cosmos 1, cosmos 2, cosmos 3). It doesn't matter is someone staked and stopped before the end of the hub.
- Governance vote, for every proposal that a wallet voted on, an extra Ion was received
- Some votes (like voting Yes on prop 14) didn't get an Ion. This could be because that upgrade from Cosmos 2 to 3 was declined, but the reason is unsure
- Being a validator didn't get any extra Ion
- Depositing for a proposal doesn't give extra ion
- Creating a proposal doesn't give extra Ion
- Staking to another validator then Sikka doesn't get Ion

**Comment by jaekwon** [comment]
Thank you Rowan!

**Comment by jaekwon** [comment]
BTW please share your osmosis addr, or we can coordinate privately.

**Comment by RowanUtrecht** [comment]
I've updated the results with my current findings
