### ISSUE TITLE
Query on 3. Retrospective on CosmosHub software contracts from the ICF and related entities

### ISSUE THREAD

**Issue by tacolopo** [gnolang/bounties-old#32]
Hello, Sam Wang said to correspond on this github page. Was looking for clarity on what exact contracts you are looking for a retrospective on / or if you are looking for someone to audit their contracts? I work at Moultrie Audits so this seems within our wheel house.

**Comment by faddat** [comment]
I've certainly had my fair share of beef with Mr JK, however here's a little bit to get you started okay?

Transparency is transparency is transparency and the beefs are irrelevant

https://twitter.com/Rarma_/status/1624740089422307329?t=G0aGZlUYdeFmKckCmQ6Ucw&s=19

**Comment by tacolopo** [comment]
@faddat well I guess the issue was either internally resolved or interest dissipated as I was never able to get any contact with gno team about working this

**Comment by faddat** [comment]
* https://www.mintscan.io/cosmos/proposals/787

But we're not done.  There's no forward looking guidance from the ICF, nor much explanation of their reasoning for moves.
