### ISSUE TITLE
Excel data Rowan

### ISSUE THREAD

**Issue by RowanUtrecht** [gnolang/bounties-old#4]
Extra data to support the manual research and proving the relation between staking at Sikka and voting

[ION Airdrop.xlsx](https://github.com/gnolang/bounties/files/6835263/ION.Airdrop.xlsx)

**Comment by jaekwon** [comment]
thank you Rowan for the manual research!  Do you have any code for it?  If not, that is OK.

this is separate from the 1000osmo bounty, of which 200 goes to Sunny (as referrer) and 800 to the ICF for providing backups of S3 data.  I am presently still trying to download said data, so it will take some time to completely verify.  Thank you Sunny and the ICF!

I have no idea what I'm doing, open to suggestions.  It seems that we will soon have blockchain data-derived ion-like distributions.  I just really want to know what ION is about.  I understand that it may be a skewed distribution, but to me the process of solving this mystery involves creating a tool that allows me to do what I want to do with Gno: airdrop according to some reasonable metric that *Gno* wants to gift to, depending on governance and staking (and other) choices.

**Comment by RowanUtrecht** [comment]
No, sorry. DOn't have any code for it. Just browsed Mintscan and copied all the addresses that staked with Sikka and voted on proposals from the Figment cosmos-3 site.

I've updated the Excel file with more conclusions and created (for the first time of my life :D) a pull request

**Comment by RowanUtrecht** [comment]
Nice that you are using this ION airdrop as input for GNO ;) Metrics that seem fair
- Staking
- Staking to multiple validators (improves decentralization)
- Staking to smaller validators  (improves decentralization)
- Staking to validators that vote
- Voting on governance

For any GNO airdrop, I would advise that staking 0.0000 are excluded. Looks like a lot of wallet still staked to Sikka, but in reality stopped. 6526 addresses all had 0 ATOM staked to SIkka, but they received 8279 ION in total. That 33% of the total airdrop.
And 446 addresses that have less then 0.1 ATOM. But still got 617 ION as group

**Comment by RowanUtrecht** [comment]
@jaekwon Don't know if you are aware pf this comment if I don't tag you. Else, sorry

**Comment by jaekwon** [comment]
Thank you Rowan!

That's really helpful.  I think some fair airdrop using our learnings for Gno sounds like a great idea.

**Comment by jaekwon** [comment]
please check this summary: https://github.com/gnolang/bounties/blob/main/bounties/001_cosmoshub_blockchain_data/README.md
