### ISSUE TITLE
Proposals for bounty division

### ISSUE THREAD

**Issue by jaekwon** [gnolang/bounties-old#7]
The 1000 osmo bounty is straightforward.
The 5000 osmo distribution needs a summary with amounts and osmo addresses,
and justification with links to all work.
The person who puts together such a document ought to be paid too.
I'll add 500 osmo in addition for anyone who proposes the winning summary of distributions.

bounty distributions should pay out some to notable contributions, but most of the bounty must go to those who completed the objectives; and moreso for extra work that makes the work/data/code usable for more use-cases. Figuring out the original hidden distribution of ION accounts is outside the scope of the bounty, but should be accounted for, but not at the expense of work/data/code generalization.

The ulterior point is to create a streamlined pipeline for bounty rewarding.
We can design processes outside of the blockchain, and code them in later.

**Comment by LL-Cosmo** [comment]
Add ions to airdrop command (Sunnya97)


https://github.com/osmosis-labs/osmosis/blob/dba2540121466e504ffee9d70f8a3410775915ee/cmd/osmosisd/cmd/genaccounts.go

**Comment by LL-Cosmo** [comment]
ION airdropped addresses and amounts

https://github.com/osmosis-labs/networks/blob/main/osmosis-1/ions.json

**Comment by jaekwon** [comment]
Thank you.  Just a reminder that the main bounty objective was for scraping the data of cosmoshub 1,2,3.  As of now AFAIK this bounty is incomplete.
