### ISSUE TITLE
scrape script for raw data

### ISSUE THREAD

**Issue by catShaark** [gnolang/bounties-old#8]
- I collect data by iterating through blocks of each chain, then decode the data to extract all the votes of gov module

**Comment by catShaark** [comment]
https://github.com/romelukaku/gaia-scraper here is my repo, I'll post the data first and then the scripts later

**Comment by jaekwon** [comment]
I just actually read this, thank you very much!
I also see your work here: https://github.com/gnolang/gno/issues/30
It looks like you are now actually scraping the raw chain data from hub 1,2,3?  If so, amazing.

**Comment by jaekwon** [comment]
Did you have to use the non-pruned database, or was the pruned one sufficient?

**Comment by catShaark** [comment]
I use the the interchain link, I don't know if it's pruned or non-pruned

**Comment by catShaark** [comment]
> I just actually read this, thank you very much!
> I also see your work here: [gnolang/gno#30](https://github.com/gnolang/gno/issues/30)
> It looks like you are now actually scraping the raw chain data from hub 1,2,3? If so, amazing.

Yess I use the raw data for the scraping

**Comment by catShaark** [comment]
do you need cosmos-hub 4 data

**Comment by catShaark** [comment]
osmo1jnqptkzgx4wpaa9kxqsfq2pfh2d56let3xmefu here is my osmo addr

**Comment by jaekwon** [comment]
thank you! https://github.com/gnolang/bounties/blob/main/bounties/001_cosmoshub_blockchain_data/README.md

**Comment by catShaark** [comment]
I also scraped data for cosmoshub-4, is it out of the scope
